### ISSUE TITLE
Improve antenna placement

### ISSUE THREAD

**Issue by marcXceeeee** [TheStaticTurtle/GarageDoorController#1]
I saw a hackaday blog post with this project. Good work!

For your next rev, you may want to consider adding a keepout under the antenna. Examples on page 2 of a similar module here: https://www.espressif.com/sites/default/files/documentation/esp-wroom-02_pcb_design_and_module_placement_guide_0.pdf

![image](https://user-images.githubusercontent.com/6755266/114667660-930bc300-9cb4-11eb-9022-c479754f5ac0.png)

**Comment by TheStaticTurtle** [comment]
True I should do it, and I'm starting to do it on other projects but I forgot here.
Thanks for the reminder tho 😄 
I doesn't seem to pose an issue with my current setup though so I'll probably keep it as is for now. If I need to add something to the board I'll try to remember it
